COCO_CLASSES = { 1: "alcohol",
    2: "anus",
    3: "blood",
    4: "breast",
    5: "cigarette",
    6: "female_genital",
    7: "gun",
    8: "insulting_gesture",
    9: "knife",
    10: "male_genital" }